### ISSUE TITLE
release → main プルリクエストのマージをトリガーとして release → develop へマージする

### ISSUE THREAD

**Issue by takada-masaya** [yanamura/git-flow-merge-action#402]
まずはじめに、素晴らしいアクションを提供いただき、ありがとうございます。

`yanamura/git-flow-merge-action` を使用するにあたって、
サンプルで提供されているようなラベルの付与ではなく、
`release` → `main` のプルリクエストがマージをされたのをトリガーとして
`release` → `develop` のマージを自動で行いたいと考えています。

```yml
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  auto-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
      - name: Extract branch name
        uses: mdecoleman/pr-branch-name@2.0.0
        id: extract_branch
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: yanamura/git-flow-merge-action@v1.2.0
        name: git-flow merge
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}
          develop_branch: "develop"
          main_branch: "main"
```

上記のような設定で実際にプルリクエストのマージを試してみると、
`release` → `develop` のマージは行われるのですが、
以下のような警告が発生します。
![image](https://user-images.githubusercontent.com/96405887/223937101-e33fb71e-6abf-4a35-b17f-fb601a76fe2c.png)

これらの警告は無視しても問題ないのか、
問題がある場合はどのような改善策があるか、
ご教授いただけますと幸いです。
よろしくお願いいたします。
